[package]
name = "book-shake"
version = "0.1.0"
authors = ["Elias Lundell <elilun03@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
